/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dados;

import java.io.File;                //Bibliotecas{
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;          //}

/**
 *
 * @author Unesp
 */
public class Janela extends javax.swing.JFrame {

    Dados objDados1; //instanciação do objeto.
    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();   //Inicia componentes da janela
        jLabel8.setVisible(false);  //Muda as fotos para invisiveis inicialmente
        jLabel9.setVisible(false);  //Muda as fotos para invisiveis inicialmente
        jLabel10.setVisible(false); //Muda as fotos para invisiveis inicialmente
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmdProcurar = new javax.swing.JButton();
        cmdConsultar = new javax.swing.JButton();
        txtConsulta = new javax.swing.JTextField();
        txtR = new javax.swing.JTextField();
        txtG = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        txtEspecie = new javax.swing.JTextField();
        txtDiretorio = new javax.swing.JTextField();
        txtNome_esp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setAutoRequestFocus(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Selecione o arquivo .arff");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setText("Consultar amostra");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, -1, -1));

        jLabel3.setText("Digite o numero da amostra a ser consultada:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 109, -1, -1));

        jLabel4.setText("R");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 174, -1, -1));

        jLabel5.setText("G");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel6.setText("B");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 226, -1, -1));

        jLabel7.setText("Espécie");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 252, -1, -1));

        cmdProcurar.setText("...");
        cmdProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdProcurarActionPerformed(evt);
            }
        });
        getContentPane().add(cmdProcurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 36, -1, -1));

        cmdConsultar.setText("Consultar");
        cmdConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(cmdConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 137, -1, -1));
        getContentPane().add(txtConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 138, 55, -1));

        txtR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRActionPerformed(evt);
            }
        });
        getContentPane().add(txtR, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 171, 55, -1));

        txtG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGActionPerformed(evt);
            }
        });
        getContentPane().add(txtG, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 197, 55, -1));
        getContentPane().add(txtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 223, 55, -1));
        getContentPane().add(txtEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 249, 54, -1));
        getContentPane().add(txtDiretorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 37, 218, -1));
        getContentPane().add(txtNome_esp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 143, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dados/newpackage/cat1.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, 210));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dados/newpackage/cat2.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, 210));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dados/newpackage/cat0.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdProcurarActionPerformed
         JFrame jFrameFC = new JFrame();    //Código fornecido pelo professor para o usuário
                                            //buscar o arquivo no PC
        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(jFrameFC);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            System.out.println("Selected file: " + selectedFile.getAbsolutePath());
            txtDiretorio.setText(selectedFile.getAbsolutePath());}        // TODO add your handling code here:
    }//GEN-LAST:event_cmdProcurarActionPerformed

    private void txtGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGActionPerformed

    }//GEN-LAST:event_txtGActionPerformed

    private void cmdConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConsultarActionPerformed
        try {               //"try e catch" a IDE cria para auxiliar.
            objDados1 = new Dados(txtConsulta.getText(), txtDiretorio.getText());
            //objDados1: objeto instanciado previamente
            //txtConsulta.getText(): Pega o texto escrito no bloco txtConsulta e atribui a primeira variavel(nº a ser consultado)
            //txtDiretorio.getText(): Pega o texto escrito no bloco txtDiretorio e atribui a segunda variavel)(diretorio do .arff)

// TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }
        objDados1.setAmos(Integer.valueOf(txtConsulta.getText()));
        
        txtR.setText(String.valueOf(objDados1.getR()));//Retorna na textbox o valor de R
        txtG.setText(String.valueOf(objDados1.getG()));//Retorna na textbox o valor de G
        txtB.setText(String.valueOf(objDados1.getB()));//Retorna na textbox o valor de B
        txtEspecie.setText(String.valueOf(objDados1.getEsp()));//Retorna na textbox o valor da espécie
        
        switch (objDados1.getEsp())             {//De acordo com o valor da espécie, retorna no textobox
            case 0:                              //o nome determinado e a sua imagem é mostrada
                txtNome_esp.setText("Coffe");
                jLabel10.setVisible(true);
                jLabel9.setVisible(false);
                jLabel8.setVisible(false);
                break;
            case 1:
                txtNome_esp.setText("Vieux farcon");
                jLabel9.setVisible(true);
                jLabel8.setVisible(false);
                jLabel10.setVisible(false);
                break;
            default:
                txtNome_esp.setText("Caricature plant");
                jLabel8.setVisible(true);
                jLabel9.setVisible(false);
                jLabel10.setVisible(false);
                break;
                
                
        
                
                
                
        }
        
    }//GEN-LAST:event_cmdConsultarActionPerformed

    private void txtRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdConsultar;
    private javax.swing.JButton cmdProcurar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtConsulta;
    private javax.swing.JTextField txtDiretorio;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtG;
    private javax.swing.JTextField txtNome_esp;
    private javax.swing.JTextField txtR;
    // End of variables declaration//GEN-END:variables
}
